Nab 377
nablarch/nablarch-fw-jaxrs pull request #16
Opened 2020-08-20 16:55 UTC by kiyohome

2020-08-21 06:46 UTC, backpaper0 requested changes

2020-08-21 06:46 UTC, backpaper0 commented on src/main/java/nablarch/fw/jaxrs/cors/BasicCors.java
> +    private String allowMethods = joinWithComma(Arrays.asList("OPTIONS", "GET", "POST", "PUT", "DELETE"));
自分で書いたコードなのですが、`PATCH`メソッドも許可しておいて良い気がしました。

2020-08-21 07:51 UTC, kiyohome commented on src/main/java/nablarch/fw/jaxrs/cors/BasicCors.java
> +    private String allowMethods = joinWithComma(Arrays.asList("OPTIONS", "GET", "POST", "PUT", "DELETE"));
PATCHを追加しました！https://github.com/nablarch/nablarch-fw-jaxrs/pull/16/commits/d57ec5329d71fb90bf36a32c25aa2203fb24afb0

2020-08-21 09:18 UTC, backpaper0 approved these changes

2020-08-28 04:11 UTC, mseko commented on src/main/java/nablarch/fw/jaxrs/ResponseFinisher.java
> +public interface ResponseFinisher {
解説書を読むと、本インターフェースはNablarch利用者実装する可能性があるよう見えます。
しかしながら、アーキテクト向け公開を表すアノテーションが付いていません。

2020-08-28 04:19 UTC, mseko commented on src/main/java/nablarch/fw/jaxrs/ResponseFinisher.java
> +public interface ResponseFinisher {
アノテーションを付与しました。

2020-08-28 04:20 UTC, mseko commented
LGTM!

2020-08-28 04:21 UTC, merged