「ボディを持たないレスポンスでもContent-Typeを設定するか否か」の処理をnablarch-fw-webに移動することに伴う修正
nablarch/nablarch-fw-jaxrs pull request #19
Opened 2021-03-05 07:12 UTC by mseko

## 背景
https://github.com/nablarch/nablarch-fw-web/pull/92 の対応に伴い、本モジュールから「ボディを持たないレスポンスでもContent-Typeを設定するか否か」を判定し処理する機能を削除

## やったこと
- https://github.com/nablarch/nablarch-fw-jaxrs/pull/13 で加えた機能を削除。
  https://github.com/nablarch/nablarch-fw-web/pull/92 の変更に合わせてユニットテストを修正。

## 確認したこと
  - https://github.com/nablarch/nablarch-fw-web/pull/92 を取り込んだ状態でユニットが成功すること。

2021-03-05 08:34 UTC, kiyohome requested changes

2021-03-05 08:34 UTC, kiyohome commented on src/test/java/nablarch/fw/jaxrs/JaxRsResponseHandlerTest.java
> -    public void testStatusCodeOnlyResponseWithSetContentTypeForResponseWithNoBody() throws Exception {
このテストは何で追加したんですか？

2021-03-08 11:10 UTC, mseko commented on src/test/java/nablarch/fw/jaxrs/JaxRsResponseHandlerTest.java
> -    public void testStatusCodeOnlyResponseWithSetContentTypeForResponseWithNoBody() throws Exception {
JaxRsResponseHandler#setSetContentTypeForResponseWithNoBodyの追加に伴うテストでした。
一度テストを消しましたが、ボディが空の場合にWebConfig#contentTypeForResponseWithNoBodyEnabledにtrueが設定されている場合のテストとして再度テストを追加しました。

2021-03-09 02:43 UTC, kumagoro1202 approved these changes

2021-03-09 05:02 UTC, kiyohome approved these changes

2021-03-16 07:59 UTC, merged