JAX-RSのボディ出力に対応したアクセスログを追加
nablarch/nablarch-fw-jaxrs pull request #28
Opened 2023-04-28 09:47 UTC by hiji

2023-05-08 04:11 UTC, kumagoro1202 requested changes

2023-05-08 04:11 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/jaxrs/JaxRsAccessLogFormatter.java
> +            String bodyString = response.getBodyString();
responseのgetBodyStringはbodyが16KB以上の場合切り捨てて先頭16KBだけを返します。
maxSizeに16KBより大きい値を入れていた場合、16KBまでしか出力されないので利用者が混乱するのでは？と思いました。

2023-05-08 04:31 UTC, kumagoro1202 requested changes

2023-05-08 04:31 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/jaxrs/JaxRsAccessLogFormatter.java
> +public class JaxRsAccessLogFormatter {
WebのHTTPアクセスログではdispatch先のクラスを出せるようにしていますが、こちらでは出さないようにしたのはどういう意図ですか？

2023-05-09 00:30 UTC, hiji commented on src/main/java/nablarch/fw/jaxrs/JaxRsAccessLogFormatter.java
> +public class JaxRsAccessLogFormatter {
現状では、dispatch先のクラス名を設定、および出力するのは[HTTPリクエストディスパッチハンドラ](https://nablarch.github.io/docs/LATEST/doc/application_framework/application_framework/handlers/web/http_request_java_package_mapping.html)を使用したときだけになっています。
JAX-RSではこのハンドラを使用する想定が基本的に無いため、出力対象から除去しました。

2023-05-09 05:55 UTC, hiji commented on src/main/java/nablarch/fw/jaxrs/JaxRsAccessLogFormatter.java
> +            String bodyString = response.getBodyString();
一時ファイルの内容を全て出力できるように対応しました。

2e59aa1f029059ecf44dadec02deac9ab97aaa09

また、maxSizeを指定して切り取った場合に、JSON構造化ログで形式を維持したまま出力できなくなったため、maxSize指定機能は除去しました。（JSON全体を文字列とすることで対応することもできましたが、ログの値を扱いづらくなると考えて対応しませんでした）

76ce6bc8926fa8196d5e55920772c8c44ceab7bb

2023-05-10 02:07 UTC, kumagoro1202 approved these changes

2023-05-10 02:07 UTC, merged