グループ指定機能を追加しました
nablarch/nablarch-fw-jaxrs pull request #35
Opened 2023-07-13 10:24 UTC by chupaaaaaaan

2023-07-19 06:46 UTC, kumagoro1202 requested changes

2023-07-19 06:46 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/jaxrs/JaxRsContext.java
> +    public Class<?> getFromAttributesOfConvertGroupAnnotation() {
メソッド名があまりに長いので情報量を増やさないAttributesという単語は省略してもいいのではと思いました。Toの方も同様。

2023-07-19 06:46 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/jaxrs/JaxRsContext.java
> +            throw new IllegalStateException("ConvertGroup annotation is not set for the resource method.");
ここでIllegalStateExceptionがスローされるのは違和感があります。コンテキストでConvertGroupが設定されていないといけないかどうかは判断できないのでは。ここではnullを返して呼び出し元で判断するべきなのではと思います。

2023-07-19 06:46 UTC, kumagoro1202 commented on src/test/java/nablarch/fw/jaxrs/JaxRsBeanValidationHandlerTest.java
> +     * {@link Groups.Test1}グループで検証される{@link Groups#name}は検証スキップされる。
何のテストかぱっと見で読み取りにくかったです。スキップされるうんぬんではなく、ConvertGroup指定がない場合はデフォルトグループで検証されると書いてくれた方がわかりやすいです。

2023-07-19 06:46 UTC, kumagoro1202 commented on src/test/java/nablarch/fw/jaxrs/JaxRsBeanValidationHandlerTest.java
> +     * {@link Valid}アノテーションと{@link ConvertGroup}アノテーションが設定されていてエラーがする場合、{@link ApplicationException}が送出されること。
日本語おかしい「エラーがする」

2023-07-19 07:44 UTC, chupaaaaaaan commented on src/main/java/nablarch/fw/jaxrs/JaxRsContext.java
> +    public Class<?> getFromAttributesOfConvertGroupAnnotation() {
Attributesを省略した名前としました。

2023-07-19 07:53 UTC, chupaaaaaaan commented on src/main/java/nablarch/fw/jaxrs/JaxRsContext.java
> +            throw new IllegalStateException("ConvertGroup annotation is not set for the resource method.");
指摘の通りと思います。

利用側では `JaxRsContext#hasConvertGroupAnnotation()` で判定しているので、単に `null` を返却するのみとしました。

2023-07-19 08:02 UTC, chupaaaaaaan commented on src/test/java/nablarch/fw/jaxrs/JaxRsBeanValidationHandlerTest.java
> +     * {@link Groups.Test1}グループで検証される{@link Groups#name}は検証スキップされる。
直接的に、「{@link ConvertGroup}が設定されていない場合、{@link Default}グループで検証される」の表現に修正しました。

2023-07-19 08:21 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/jaxrs/JaxRsContext.java
> +            throw new IllegalStateException("ConvertGroup annotation is not set for the resource method.");
nullが帰る呼び方はされないとしても
`jaxRsContext.getFromOfConvertGroupAnnotation().equals(Default.class)`という書き方はNPEが出るのではないかと気持ち悪いです。Classの比較なら単なる比較演算子でいいと思います。またはDefault.classを左辺に持ってくるべきだと思います。

2023-07-19 08:27 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/jaxrs/JaxRsContext.java
> +            throw new IllegalStateException("ConvertGroup annotation is not set for the resource method.");
`JaxRsContextTest`に`import static org.junit.Assert.fail;`が残ってる。

2023-07-19 08:34 UTC, kumagoro1202 requested changes

2023-07-19 08:34 UTC, kumagoro1202 commented on src/test/java/nablarch/fw/jaxrs/JaxRsBeanValidationHandlerTest.java
> +        assertThat("バリデーションエラーは発生しないので後続のハンドラの結果が戻されること", result, is("ok"));
`org.junit.Assert.assertThat`は`Deprecated`なので`org.hamcrest.MatcherAssert.assertThat;`に変えてください。

2023-07-19 09:34 UTC, chupaaaaaaan commented on src/main/java/nablarch/fw/jaxrs/JaxRsContext.java
> +            throw new IllegalStateException("ConvertGroup annotation is not set for the resource method.");
比較演算子での比較としました。
また残っていた不要import文も削除しました。

2023-07-19 09:35 UTC, chupaaaaaaan commented on src/test/java/nablarch/fw/jaxrs/JaxRsBeanValidationHandlerTest.java
> +        assertThat("バリデーションエラーは発生しないので後続のハンドラの結果が戻されること", result, is("ok"));
修正しました。
合わせてJaxRsContextTest.javaの方も、同様に対応しました。

2023-07-20 06:43 UTC, kumagoro1202 approved these changes

2023-07-20 06:43 UTC, merged

2023-07-25 05:31 UTC, kumagoro1202 commented
レビュー1回目
実施日:2023/07/19
開始:15:30
終了:17:30
レビュー時間:20