HttpRequest#getParam、getParamMapを呼び出すユーティリティを追加
nablarch/nablarch-fw-jaxrs pull request #38
Opened 2024-02-20 10:39 UTC by oguchi-shiori03

2024-02-21 02:49 UTC, kumagoro1202 requested changes

2024-02-21 02:49 UTC, kumagoro1202 commented on src/test/java/nablarch/fw/jaxrs/JaxRsBeanUtilTest.java
> +     * HTTPリクエストからBeanが生成され、バリデーションエラーが発生しないこと
コメントとテスト内容が乖離しています。

2024-02-21 02:49 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/jaxrs/JaxRsBeanUtil.java
> +public final class JaxRsBeanUtil {
公開APIにしてください。

2024-02-21 10:02 UTC, oguchi-shiori03 commented on src/test/java/nablarch/fw/jaxrs/JaxRsBeanUtilTest.java
> +     * HTTPリクエストからBeanが生成され、バリデーションエラーが発生しないこと
コメントの内容を修正しました。

2024-02-21 10:03 UTC, oguchi-shiori03 commented on src/main/java/nablarch/fw/jaxrs/JaxRsBeanUtil.java
> +public final class JaxRsBeanUtil {
@Publisedアノテーションを追加しました。

2024-02-27 07:53 UTC, kumagoro1202 requested changes

2024-02-27 07:53 UTC, kumagoro1202 commented on src/main/java/nablarch/fw/jaxrs/JaxRsHttpRequest.java
> + * JAX-RS用の{@link HttpRequest}クラス。
HttpRequestと何が違うのかを明記してほしいです。特定のメソッドを公開APIにしてることと、それ以外のメソッドは保持するHttpRequestに委譲してることを書いてください。

ついでにgetParamMap、getParam、getPathParamはコンストラクタの直後にくるように順番変えてほしいです。

2024-02-27 07:53 UTC, kumagoro1202 commented on src/test/java/nablarch/fw/jaxrs/JaxRsHttpRequestTest.java
> +        assertThat(sut.getMethod(), is("GET"));
この辺のassertは全部委譲してるので、MockHttpRequestを変数化してそれぞれの戻り値と一致することのテストにしたほうがいいです。
```java
    public void testGetMethod() {
        MockHttpRequest delegate = new MockHttpRequest();
        JaxRsHttpRequest sut = new JaxRsHttpRequest(delegate);
        assertThat(sut.getMethod(), is(delegate.getMethod()));
    }
```

2024-02-27 09:09 UTC, oguchi-shiori03 commented on src/main/java/nablarch/fw/jaxrs/JaxRsHttpRequest.java
> + * JAX-RS用の{@link HttpRequest}クラス。
クラスコメントを追記しました。
また、getParamMap、getParam、getPathParamがコンストラクタの直後にくるように移動しました。

2024-02-27 09:10 UTC, oguchi-shiori03 commented on src/test/java/nablarch/fw/jaxrs/JaxRsHttpRequestTest.java
> +        assertThat(sut.getMethod(), is("GET"));
assertの比較をHttpRequestの委譲メソッドと行うように変更しました。

2024-02-28 04:16 UTC, kumagoro1202 requested changes

2024-02-28 04:16 UTC, kumagoro1202 commented on src/test/java/nablarch/fw/jaxrs/JaxRsHttpRequestTest.java
> +        assertThat(sut.getUserAgent().getOsVersion(), is(delegate.getUserAgent().getOsVersion()));
ここだけUserAgentの比較じゃなくUserAgentのgetまで呼び出しているのは何か意図がありますか？
（equalsを独自実装してて中身まで見ないとだめとかかと思いましたがUserAgent見ても独自実装はなさそうだったので確認です。）

2024-02-28 04:26 UTC, oguchi-shiori03 commented on src/test/java/nablarch/fw/jaxrs/JaxRsHttpRequestTest.java
> +        assertThat(sut.getUserAgent().getOsVersion(), is(delegate.getUserAgent().getOsVersion()));
[HttpRequest#getUserAgent](https://github.com/nablarch/nablarch-fw-web/blob/80daa77b0d1f535000f59df503dd44348f100f08/src/main/java/nablarch/fw/web/HttpRequest.java#L237-L241)では都度UserAgentのインスタンスを生成していて、UserAgent同士を比較するとassertエラーになってしまうため、フィールド同士を比較して同一のUserAgentが生成されていることを確認しています。

2024-02-28 04:31 UTC, kumagoro1202 approved these changes

2024-02-28 04:32 UTC, merged